on:
  pull_request:
    branches:
      prestaging
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
